version: "3"

services:
  mysqldb:
    container_name: mysqlCICD
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: examiheb
      MYSQL_ROOT_PASSWORD: ihebihebiheb
  app:
    depends_on:
      - mysqldb
    image: ihebsahli/devops
    restart: always
    ports:
      - 8089:8089
      
    environment: 
      
       - spring.datasource.url=jdbc:mysql://mysql:3306/examiheb?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false 
       - spring.datasource.username=root 
       - spring.datasource.password=ihebihebiheb 
       
      
volumes:
  db: